# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Contador.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-backend:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
      - name: Descargar el c贸digo
        uses: actions/checkout@v2
      - name: Setup Node.js utilizando versi贸n ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instalar las dependencias
        run: npm install
        working-directory: ./backend
      - name: Ejecutar los tests
        run: npm test
        working-directory: ./backend

  publish-backend:
    runs-on: ubuntu-latest

    needs: build-backend

    steps:
      - name: Descargar el c贸digo
        uses: actions/checkout@v2
      - name: Deploy en Heroku
        uses: akhileshns/heroku-deploy@v3.8.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "github-actions-example-nodejs"
          heroku_email: "lszikora@dblandit.com"
          appdir: ./backend

  build-frontend:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js utilizando versi贸n 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Instalar las dependencias
        run: npm install
        working-directory: ./frontend
      - name: Configurar credenciales git
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${token}@github.com/${repository}
        env:
          user_name: 'lszikoradblandit'
          user_email: 'lszikora@dblandit.com'
          token: ${{ secrets.GH_PAGES_TOKEN }}
          respository: ${{ github.repository }}
      - name: Desplegar la app en GH Pages
        run: |
          git remote get-url origin
          cd ./frontend
          git remote get-url origin
          npm run clean
          npm run deploy